# Generated by Django 4.1.7 on 2023-03-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.FloatField()),
                ('two', models.FloatField()),
                ('three', models.FloatField()),
                ('four', models.FloatField()),
                ('five', models.FloatField()),
                ('six', models.FloatField()),
                ('seven', models.FloatField()),
                ('eight', models.FloatField()),
                ('nine', models.FloatField()),
                ('ten', models.FloatField()),
                ('eleven', models.FloatField()),
                ('twelve', models.FloatField()),
                ('thirteen', models.FloatField()),
                ('fourteen', models.FloatField()),
                ('fifteen', models.FloatField()),
                ('sixteen', models.FloatField()),
                ('seventeen', models.FloatField()),
                ('eighteen', models.FloatField()),
            ],
        ),
    ]
